image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - .m2/repository/

stages:
 - build
 - test
 - package
 - deploy

build:
 stage: build
 script:
   - mvn compile 

test:
 stage: test
 script:
   - mvn test

package:
 stage: package
 rules:
   - if: '$CI_COMMIT_TAG =~ /^.*-rc.*$/'
 script:
   - mvn -DskipTests=true package
 artifacts:
   paths:
       - target/*.jar

deploy:
 stage: deploy
 rules:
   - if: '$CI_COMMIT_TAG =~ /^.*-rc.*$/'
 dependencies:
   - build
   - test
   - package
 image: docker:19.03.13
 services:
  - docker:19.03.13-dind
 before_script:
   - docker info
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
 script:
   - docker pull $CI_REGISTRY_IMAGE:latest || true
   - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
   - docker push $CI_REGISTRY_IMAGE:latest
