image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

stages:
 - build
 - test
 - package
 - deploy

build:
 stage: build
 script:
   - mvn compile 

test:
 stage: test
 script:
   - mvn test

package:
 stage: package
 rules:
   - if: '$CI_COMMIT_TAG =~ /^.*-rc.*$/'
 script:
   - mvn -DskipTests=true package
 artifacts:
   paths:
       - target/*.war

deploy:
 stage: deploy
 rules:
   - if: '$CI_COMMIT_TAG =~ /^.*-rc.*$/'
 dependencies:
   - build
   - test
   - package
 image: jboss/wildfly
 script:
   - /opt/jboss/wildfly/bin/jboss-cli.sh --connect --controller=${HOST_WILDFLY} --user=${USER_WILDFLY} --password=${PASS_WILDFLY} --commands="deploy target/*.war --force"

